using DataGateMonitor.DataBase.Contexts;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataGateMonitor.DataBase.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260823120000_VpnServerDiscoveries_Init")]
public partial class VpnServerDiscoveries_Init : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS xgb_dashopnvpn."VpnServerDiscoveries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ServerType" integer NOT NULL DEFAULT 0,
                "ApiUrl" character varying(512) NOT NULL,
                "SuggestedName" character varying(128) NULL,
                "PublicIp" character varying(64) NULL,
                "Version" character varying(64) NULL,
                "IsEnableWss" boolean NOT NULL DEFAULT FALSE,
                "Status" integer NOT NULL DEFAULT 0,
                "LastSeenUtc" timestamp with time zone NOT NULL,
                "LastNotifiedUtc" timestamp with time zone NULL,
                "ResolvedVpnServerId" integer NULL,
                "RejectedAt" timestamp with time zone NULL,
                "RejectReason" character varying(512) NULL,
                "CreateDate" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "LastUpdate" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "PK_VpnServerDiscoveries" PRIMARY KEY ("Id")
            );

            CREATE INDEX IF NOT EXISTS "IX_VpnServerDiscoveries_Status"
                ON xgb_dashopnvpn."VpnServerDiscoveries" ("Status");

            CREATE INDEX IF NOT EXISTS "IX_VpnServerDiscoveries_ApiUrl"
                ON xgb_dashopnvpn."VpnServerDiscoveries" ("ApiUrl");

            CREATE INDEX IF NOT EXISTS "IX_VpnServerDiscoveries_LastSeenUtc"
                ON xgb_dashopnvpn."VpnServerDiscoveries" ("LastSeenUtc");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_VpnServerDiscoveries_ApiUrl_Pending"
                ON xgb_dashopnvpn."VpnServerDiscoveries" ("ApiUrl")
                WHERE "Status" = 0;
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP INDEX IF EXISTS xgb_dashopnvpn."IX_VpnServerDiscoveries_ApiUrl_Pending";
            DROP INDEX IF EXISTS xgb_dashopnvpn."IX_VpnServerDiscoveries_LastSeenUtc";
            DROP INDEX IF EXISTS xgb_dashopnvpn."IX_VpnServerDiscoveries_ApiUrl";
            DROP INDEX IF EXISTS xgb_dashopnvpn."IX_VpnServerDiscoveries_Status";
            DROP TABLE IF EXISTS xgb_dashopnvpn."VpnServerDiscoveries";
            """);
    }
}
