using DataGateMonitor.DataBase.Contexts;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataGateMonitor.DataBase.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260816120000_VpnServerGroups_Init")]
public partial class VpnServerGroups_Init : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS xgb_dashopnvpn."VpnServerGroups" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" character varying(64) NOT NULL,
                "SortOrder" integer NOT NULL DEFAULT 0,
                "CreateDate" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "LastUpdate" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT "PK_VpnServerGroups" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_VpnServerGroups_Name"
                ON xgb_dashopnvpn."VpnServerGroups" ("Name");

            CREATE INDEX IF NOT EXISTS "IX_VpnServerGroups_SortOrder"
                ON xgb_dashopnvpn."VpnServerGroups" ("SortOrder");

            ALTER TABLE xgb_dashopnvpn."VpnServers"
                ADD COLUMN IF NOT EXISTS "VpnServerGroupId" integer NULL;

            ALTER TABLE xgb_dashopnvpn."VpnServers"
                ADD COLUMN IF NOT EXISTS "SortOrder" integer NOT NULL DEFAULT 0;

            CREATE INDEX IF NOT EXISTS "IX_VpnServers_VpnServerGroupId"
                ON xgb_dashopnvpn."VpnServers" ("VpnServerGroupId");

            CREATE INDEX IF NOT EXISTS "IX_VpnServers_VpnServerGroupId_SortOrder"
                ON xgb_dashopnvpn."VpnServers" ("VpnServerGroupId", "SortOrder");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_VpnServers_VpnServerGroups_VpnServerGroupId'
                ) THEN
                    ALTER TABLE xgb_dashopnvpn."VpnServers"
                        ADD CONSTRAINT "FK_VpnServers_VpnServerGroups_VpnServerGroupId"
                        FOREIGN KEY ("VpnServerGroupId")
                        REFERENCES xgb_dashopnvpn."VpnServerGroups" ("Id")
                        ON DELETE SET NULL;
                END IF;
            END $$;
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            ALTER TABLE xgb_dashopnvpn."VpnServers"
                DROP CONSTRAINT IF EXISTS "FK_VpnServers_VpnServerGroups_VpnServerGroupId";

            DROP INDEX IF EXISTS xgb_dashopnvpn."IX_VpnServers_VpnServerGroupId_SortOrder";
            DROP INDEX IF EXISTS xgb_dashopnvpn."IX_VpnServers_VpnServerGroupId";

            ALTER TABLE xgb_dashopnvpn."VpnServers"
                DROP COLUMN IF EXISTS "SortOrder";

            ALTER TABLE xgb_dashopnvpn."VpnServers"
                DROP COLUMN IF EXISTS "VpnServerGroupId";

            DROP TABLE IF EXISTS xgb_dashopnvpn."VpnServerGroups";
            """);
    }
}
